/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-container": "#cad3ff",
        "error": "#ba1a1a",
        "tertiary-fixed": "#95f8a7",
        "inverse-on-surface": "#eaf1ff",
        "surface": "#f8f9ff",
        "secondary-container": "#dae2fd",
        "on-tertiary-container": "#88ea9a",
        "surface-tint": "#2151da",
        "on-primary-fixed": "#001551",
        "tertiary-container": "#006b2f",
        "on-primary": "#ffffff",
        "inverse-primary": "#b7c4ff",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-container-highest": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed": "#131b2e",
        "outline-variant": "#c4c5d7",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#dce1ff",
        "on-tertiary-fixed-variant": "#005323",
        "background": "#f8f9ff",
        "secondary-fixed": "#dae2fd",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-container": "#1d4ed8",
        "surface-container": "#e5eeff",
        "surface-dim": "#cbdbf5",
        "inverse-surface": "#213145",
        "surface-variant": "#d3e4fe",
        "secondary": "#565e74",
        "primary-fixed-dim": "#b7c4ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#0039b5",
        "on-surface-variant": "#434655",
        "surface-bright": "#f8f9ff",
        "on-secondary-container": "#5c647a",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30",
        "tertiary-fixed-dim": "#79db8d",
        "outline": "#747686",
        "on-tertiary-fixed": "#00210a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface": "#0b1c30",
        "tertiary": "#005022",
        "primary": "#0037b0",
        "warning": "#d97706"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-tablet": "1.25rem",
        "margin-desktop": "2rem",
        "space-xs": "0.25rem",
        "margin": "1rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "margin-tablet": "1.5rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem"
      },
      fontFamily: {
        "body-lg": ["Public Sans", "sans-serif"],
        "code-xs": ["JetBrains Mono", "monospace"],
        "headline-md": ["Public Sans", "sans-serif"],
        "label-lg": ["Public Sans", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-xl-mobile": ["Public Sans", "sans-serif"],
        "body-sm": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "headline-sm": ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "headline-xl": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "label-sm": ["Public Sans", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "code-xs": ["10px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "code-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-xl-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-xl": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
};
